version: '3'

services:
  dev:
    build:
      context: ..
      dockerfile: Dockerfile/Dockerfile
    image: stable-diffusion-webui:1.4.0
    container_name: stable-diffusion-webui
    volumes:
      - ../models/embeddings:/stable-diffusion-webui/embeddings
      - ../models/Lora:/stable-diffusion-webui/models/Lora
      - ../models/control-net:/stable-diffusion-webui/extensions/sd-webui-controlnet/models
      - ../outputs:/stable-diffusion-webui/outputs
    working_dir: /stable-diffusion-webui
    tty: true
    ports:
      - "7860:7860"
    entrypoint: sh -c "python launch.py --skip-version-check --listen --enable-insecure-extension-access"

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
