version: '3'

services:
  stable-diffusion-webui:
    build:
      context: ../Dockerfile
      dockerfile: Dockerfile
    image: stable-diffusion-webui:1.10.0-sdxl
    container_name: stable-diffusion-webui
    volumes:
      - ../models/embeddings:/stable-diffusion-webui/embeddings
      - ../models/Lora:/stable-diffusion-webui/models/Lora
      - ../outputs:/stable-diffusion-webui/outputs
    working_dir: /stable-diffusion-webui
    tty: true
    ports:
      - "7860:7860"
    entrypoint: sh -c "python launch.py --listen --no-download-sd-model --xformers --enable-insecure-extension-access"

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
